### ISSUE TITLE
Initial tag should be v0.1.0

### ISSUE THREAD

**Issue by hairmare** [graviphoton/angular-rql-query-generator#1]
Since this should follow http://semver.org/spec/v2.0.0.html, ``v0.1`` is not really valid.

Also, you should initialize the ``git-flow`` stuff next... Start by pushing a develop branch and then switch the default branch of this repo to it. Next use ``git flow release`` to tag a proper release.

You should be using git-flow release for everything related to tagging, this ensures that everyone does this in a consistent way. Also, just ignore the github releases "Publish" button until after your tag has been pushed and don't mark it as "Pre-Release", this is obvious for 0.x releases that follow semver, later there are ``-alphaN``, ``-betaN`` and ``-rcN`` tags that fulfill the same purpose.

**Comment by RamonB** [comment]
Thanks for your feedback. It's fixed now.
